### PR TITLE
Add setup files

### PR DESCRIPTION
**Pull request by yyoncho**

### CODE REVIEW

**Review by emizzle — APPROVED** [review]
LGTM

**Comment by emizzle** [comment]
Just nitpicking, but could you add a newline at the end of `nimble.lock`, please?

**Comment by yyoncho** [comment]
> Just nitpicking, but could you add a newline at the end of `nimble.lock`, please?

It is autogenerated file, if we want that we should change `nimble`

**Comment by emizzle** [comment]
Of course, good point, my bad 😄

**Pull request merged**
