### PR TITLE
feat: merge add/get providers with discv5

### LINKED ISSUE #12: Move Add/Get Provider from talk to `eth/p2p/discoveryv5/messages`

### PR DESCRIPTION
**Pull request by emizzle**
Closes #12.

Merge the add/get providers messages with the discovery v5 messages inside of the discovery v5 code. Discovery v5 uses RLP encoding, while the add/get providers uses protobufs, as per the libp2p spec. The merge of these two uses RLP on the outer wrapper of the message, and a protobuf-encoded blob on the “inside” for the add/get providers messages only. Eventually this needs to change so that we use protobufs only.

There is still some code in the libp2pdht/dht directory, which is being read from the discovery v5 directory. Eventually these two should merge as well.

### CODE REVIEW

**Comment by cskiraly** [comment]
Looking through the code, I was thinking whether we should still keep the Providers logic and related data structures in a separate file. What do you think, would that be meaningful?

**Comment by emizzle** [comment]
The file likely should be broken up in to smaller pieces, and this could be a step in the right direction, I do agree. Most of the providers code will be easy to move to a separate file. However there will be some pieces that will not be as easy to separate, such as the encoding/decoding logic, which is a bit convoluted because it's mixed with RLP in the meantime. For now, I can move the east bits, and then maybe we can move more later.

**Comment by emizzle** [comment]
@cskiraly I took a stab at this, and it's not as easy as I thought due to circular dependencies. 

When we pull out the providers, there is going to be a reliance on adding/getting providers locally, which the providers need to do, as well as when messages are received (in discv5). I thought one workaround might have been to pull out commonly accessed code to a common file that both import, but it didn't work because the common file would still need to access `type Protocol` which is is discv5. We could also pull the type out, but organisationally it will feel a bit messy.

What is the main reason for wanting to pull out the code? Is it for the ability to merge upstream nim-eth/discv5 changes later?

**Review by cskiraly — APPROVED** [review]
looks good

**Pull request merged**
