### PR TITLE
Switch to libp2p crypto

### LINKED ISSUE #2: Use libp2p crypto instead of nim-eth/keys
Use libp2p crypto instead of all other cryptos (eth/keys, nimcrypto, etc).

In libp2p, can be secp256k1 or a few others. We are only going to use secp256k1.

### PR DESCRIPTION
**Pull request by Menduist**
Still need to update the test with valid keys etc

closes #2

### CODE REVIEW

**Comment by Menduist** [comment]
Note: nim-libp2p supports more than just Secp256k1:
rsa,ed25519,secp256k1,ecnist

I don't know if we can do ECDH with every scheme in this list (notably, I don't think it's possible with rsa)

Currently, this PRs only support secp256k1 (so we have to compile with `-d:libp2p_pki_schemes=secp256k1`)
In the future, to continue supporting UDP, we'll always have to disable at least RSA in the projects using nim-libp2p-dht.

ofc, with the libp2p transport, we don't have to secure the connection here, so we will be able to use whatever we want

**Comment by cskiraly** [comment]
right, the plan was to go for Secp256k1 only, and deal with eventual others only if some application happens to use them for IDs.

As for the libp2p transport: that skips many of the files related to the UDP transport. The UDP transport is an "EncyptedAuthenticadTransport" and includes a number of files, such as transport.nim, session.nim, and parts of encoding.nim. Most of these are not needed when we use a libp2p transport.

**Comment by emizzle** [comment]
Not trying to step on any toes at all, but I went ahead and finished the move over to libp2p crypto: https://github.com/status-im/nim-libp2p-dht/pull/32.

I had already climbed a few mountains and it would have been painful for you have to repeat that work. The last tests that needed to be fixed, I was able to fix using some of the work done for dht protobufs where the expected encodings had changed, and this was also the case when we swapped out crypto schemes.

**Comment by Menduist** [comment]
Don't worry, I didn't spent too much time on this, fortunately ;)
Closing in favor of yours, not sure if parts of mine are worth saving

**Comment by Menduist** [comment]
@emizzle
Maybe I missed something, but currently, my branch is only failing on `test_discoveryv5_encoding.nim` (because the encoding actually changed), whereas yours have fails on other tests, so mine may actually be closer

I'll let you do what you want, either finish up mine, or pick some part of it for yours, or just finish up yours :wink:

**Comment by emizzle** [comment]
Ended up using a bit from both (left the other PR open), thank you!

**Pull request closed without merging**
